// Couche métier, rangée par fonctionnalité : une fonctionnalité = un dossier (service, schémas, tests).
export {
  AuditEventInput,
  recordAuditEvent,
  scrubDetails,
  type AuditEventInputValue,
} from './audit/recordAuditEvent.ts';
export { checkHealth, type HealthProbe, type HealthReport } from './health/checkHealth.ts';
export { createLogger, REDACTED_KEYS, type Logger } from './logging/createLogger.ts';
export {
  ensurePersonalOrganization,
  kindOf,
  listUserOrganizations,
  memberRole,
  metadataFor,
  preferredOrganizationId,
  slugFor,
  type OrganizationKind,
  type UserOrganization,
} from './accounts/organizations.ts';
export { findCustomers, type CustomerSummary } from './accounts/customers.ts';
export {
  grantStaffRole,
  accountIdByEmail,
  isStaffRole,
  listStaff,
  staffMemberById,
  revokeStaffRole,
  rolesOf,
  STAFF_ROLES,
  StaffError,
  staffRolesOf,
  type StaffRole,
} from './accounts/staff.ts';
export { hasMcpConnection, listMcpConnections, revokeMcpConnection, type McpConnection } from './mcp/connections.ts';
export {
  CatalogError,
  daysLabel,
  FeatureInput,
  getCatalogProduct,
  listProducts,
  NATURES,
  pick,
  planCodeOf,
  ProductInput,
  upsertFeature,
  upsertProduct,
  type Actor,
  type CatalogEdition,
  type CatalogErrorCode,
  type CatalogLicenseType,
  type CatalogProduct,
  type LicenseTypeNature,
  type Locale,
  type ProductStatus,
} from './catalog/catalog.ts';
export {
  applyChange,
  CatalogChange,
  CatalogDocument,
  changeCatalog,
  diffCatalog,
  discardCatalogDraft,
  documentOf,
  EditionFields,
  getCatalogEditing,
  LicenseTypeFields,
  publishCatalog,
  validateDocument,
  type CatalogDiff,
  type CatalogEditing,
  type DocEdition,
  type DocLicenseType,
} from './catalog/draft.ts';
export {
  emptyValue,
  emptyValues,
  MEDIA_REF,
  SAFE_HREF,
  zodForField,
  zodForFields,
  type Field,
  type FieldLabel,
  type Fields,
  type LinkValue,
} from './content/fields.ts';
export {
  BLOCK_TYPES,
  blockDefinition,
  BLOCKS,
  blockSchema,
  blocksSchema,
  type Block,
  type BlockDefinition,
} from './content/blocks.ts';
export { renderInlineMarkdown, renderMarkdown, slugify, type TocEntry } from './content/markdown.ts';
export {
  DraftInput,
  ensurePage,
  findPageId,
  getPageForEditing,
  getPreviewPage,
  getPublishedPage,
  listPages,
  PAGE_KEY,
  PageError,
  publishDraft,
  restoreVersion,
  saveDraft,
  type PageContent,
  type PageRef,
} from './content/pages.ts';
export {
  createLocalMediaStorage,
  createS3MediaStorage,
  MEDIA_KEY,
  type MediaStorage,
  type S3Config,
  type StoredObject,
} from './media/storage.ts';
export {
  collectMediaRefs,
  listMedia,
  MAX_UPLOAD_BYTES,
  MediaError,
  MediaTextInput,
  mediaUrl,
  registerStaticImage,
  resolveMedia,
  updateMediaTexts,
  uploadImage,
  type ResolvedMedia,
} from './media/media.ts';
export { SEED_PAGES, seedInitialContent, type SeedPage } from './seed/pages.ts';
export { prepareBlocks, type PreparedBlock, type RenderedMarkdown } from './content/prepare.ts';
export {
  createLicenseSigner,
  decryptLicenseKey,
  encryptLicenseKey,
  generateLicenseKey,
  generateSigningKey,
  licenseKeyHash,
  normalizeLicenseKey,
  type LicensePayload,
  type LicenseSigner,
} from './licenses/crypto.ts';
export {
  activateLicense,
  CHANNELS,
  claimLicenseByKey,
  claimLicensesForEmail,
  DAY,
  editionDescriptors,
  extendLicense,
  findLicenses,
  getLicense,
  getLicensesByIds,
  IssueInput,
  issueLicense,
  LICENSE_VIEWS,
  LicenseError,
  LicenseFilters,
  licenseJournal,
  listLicensesForOrganizations,
  OFFLINE_DAYS,
  organizationForEmail,
  recordSeatInvite,
  refreshLicense,
  releaseDevice,
  releaseSeat,
  revokeLicense,
  setLicenseSeats,
  type ActivateError,
  type IssueInputValue,
  type LicenseChannel,
  type LicenseDependencies,
  type LicenseErrorCode,
  type LicenseView,
  type LicenseViewName,
  type RefreshError,
} from './licenses/licenses.ts';
export {
  BatchInput,
  extendBatch,
  extendLicenses,
  generateBatch,
  getBatch,
  licenseKeysCsv,
  listBatches,
  MAX_BATCH,
  resendBatchMails,
  resendLicenseKey,
  revokeBatch,
  revokeLicenses,
  uniqueEmails,
  type BatchInputValue,
  type BatchSummary,
} from './licenses/batches.ts';
export { findLicenseHolders, type LicenseHolder } from './licenses/holders.ts';
export {
  claimDueJobs,
  completeJob,
  countFailedJobs,
  enqueueJob,
  failJob,
  listJobs,
  retryJob,
  runDueJobs,
  type JobHandlers,
  type JobKind,
} from './jobs/jobs.ts';
export { dashboardStats, PERIODS, type DashboardStats, type Period } from './stats/stats.ts';
export { JournalFilters, listJournal } from './audit/journal.ts';
